name: logger_flutter_plus
description: Flutter extension for logger. Please go there for documentation.
version: 1.0.0

homepage: https://github.com/Oliinyk-Volodymyr/logger_flutter

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  logger: ^1.1.0
  collection: ^1.16.0
  sensors_plus: ^2.0.1